# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

env_vars:
  global:
    - RGL_USE_NULL=TRUE

services:
  - xvfb

r_binary_packages:
  - rgl

r_packages:
  - covr
  - smoother

r_github_packages:
  - nategarton13/bulletcp

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

after_success:
  - Rscript -e 'covr::codecov()'
