# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

addons:
  apt:
    update: true
    packages:
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev

env_vars:
  global:
    - RGL_USE_NULL=TRUE

services:
  - xvfb

r_binary_packages:
  - rgl

r_packages:
  - covr
  - smoother
  - assertthat
  - ggplot2
  - MASS
  - purrr
  - imager
  - locfit
  - zoo
  - magrittr
  - dplyr

r_github_packages:
  - nategarton13/bulletcp
  - heike/x3ptools

after_success:
  - Rscript -e 'covr::codecov()'
